# Generated by Django 3.0.4 on 2020-04-01 06:47

import api.models.slot
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[(api.models.slot.SlotStatus['AVAILABLE'], 'Available'), (api.models.slot.SlotStatus['COMPLETED'], 'Completed'), (api.models.slot.SlotStatus['EXPIRED'], 'Expired'), (api.models.slot.SlotStatus['BOOKED'], 'Booked')], max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slot',
                'managed': True,
            },
        ),
    ]
