# Generated by Django 3.0.4 on 2020-04-01 08:14

import api.models.slot
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[(api.models.slot.SlotStatus['AVAILABLE'], 'Available'), (api.models.slot.SlotStatus['COMPLETED'], 'Completed'), (api.models.slot.SlotStatus['EXPIRED'], 'Expired'), (api.models.slot.SlotStatus['BOOKED'], 'Booked')], default=api.models.slot.SlotStatus['AVAILABLE'], max_length=50),
        ),
    ]
